import { useEffect, useRef, useState } from "react";
import { Behavior, ControlNode, Diagram } from "@mindfusion/diagramming";
import { DiagramView } from "@mindfusion/diagramming-react";
import { Rect } from "@mindfusion/drawing";

const cards = [{ id: 1, nickname: "민트", intro: "UI 흐름 설계", color: "#2b8a78" }, { id: 2, nickname: "라온", intro: "데이터 시각화", color: "#6f5bd3" }];
const avatar = (card) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60"><circle cx="30" cy="30" r="30" fill="${card.color}"/><text x="30" y="38" text-anchor="middle" font-family="sans-serif" font-size="22" fill="white">${card.nickname[0]}</text></svg>`)}`;
const expandedHtml = () => `<section data-mf-card-node="13-02" data-expanded="true" style="box-sizing:border-box;width:100%;height:100%;display:grid;gap:8px;padding:10px;border:3px solid #2468d6;border-radius:14px;background:#edf5ff">${cards.map((card) => `<article data-card-id="${card.id}" style="display:flex;gap:10px;align-items:center;padding:8px;border-radius:10px;background:white"><img src="${avatar(card)}" alt="${card.nickname}" style="width:38px;height:38px;border-radius:50%"><div><strong style="display:block;font:700 14px sans-serif;color:#17345f">${card.nickname}</strong><span style="font:12px sans-serif;color:#61708a">${card.intro}</span></div></article>`).join("")}</section>`;

export default function Step1302ExpandSelected({ onStatus } = {}) {
  const [diagram] = useState(() => new Diagram()); const viewRef = useRef(null); const initialized = useRef(false); const nodeRef = useRef(null); const [expanded, setExpanded] = useState(false); const events = useRef(0);
  const report = (isExpanded) => onStatus?.({ diagramReady: true, viewReady: true, rendered: true, nodeCount: 1, linkCount: 0, htmlDomCount: 1, buttonDomCount: 0, cardCount: cards.length, cardDomCount: isExpanded ? cards.length : 0, selectedNodeCount: isExpanded ? 1 : 0, cardExpanded: isExpanded, selectedCardCount: 0, eventCount: events.current, lastEvent: isExpanded ? "선택하여 카드 펼침" : "선택 대기", consoleErrorCount: 0 });
  const initialize = () => { if (initialized.current) return; const coreView = viewRef.current?.find(); if (!coreView) return; initialized.current = true; const node = new ControlNode(coreView); node.template = '<section data-mf-card-node="13-02" data-expanded="false" style="box-sizing:border-box;width:100%;height:100%;display:grid;place-items:center;padding:12px;border:2px solid #8ba9d0;border-radius:14px;background:#f7fbff;font:700 15px sans-serif;color:#17345f">팀 카드 2명 · 선택하여 펼치기</section>'; node.bounds = new Rect(65, 40, 110, 34); nodeRef.current = node; diagram.addItem(node); };
  const domCreated = () => report(false);
  const selectionChanged = () => { const node = nodeRef.current; const content = node?.getContent?.(); if (!content) return; const selected = diagram.selection.nodes.includes(node); if (selected) { events.current += 1; content.innerHTML = expandedHtml(); node.bounds = new Rect(56, 18, 122, 60); diagram.invalidate(); } setExpanded(selected); report(selected); };
  useEffect(() => () => diagram.clearAll(), [diagram]);
  return <div data-testid="diagram-demo"><p data-testid="expand-state">{expanded ? "선택 1개 · 확장 상태 · 카드 DOM 2개" : "선택 0개 · 축약 상태"}</p><button type="button" onClick={() => diagram.selection.addItem(nodeRef.current)}>노드 선택</button><div style={{ height: 430 }}><DiagramView ref={viewRef} diagram={diagram} behavior={Behavior.Modify} onControlLoaded={initialize} onNodeDomCreated={domCreated} onSelectionChanged={selectionChanged} style={{ width: "100%", height: "100%" }} /></div></div>;
}
