import { useEffect, useRef, useState } from "react";
import { Behavior, ControlNode, Diagram } from "@mindfusion/diagramming";
import { DiagramView } from "@mindfusion/diagramming-react";
import { Rect } from "@mindfusion/drawing";

const cards = [{ id: 1, nickname: "민트", intro: "UI 설계", color: "#2b8a78" }, { id: 2, nickname: "라온", intro: "시각화", color: "#6f5bd3" }, { id: 3, nickname: "하루", intro: "UX 연구", color: "#d06b45" }];

export default function Step1404CardClickSelection({ onStatus } = {}) {
  const [diagram] = useState(() => new Diagram()); const viewRef = useRef(null); const initialized = useRef(false); const listeners = useRef(new Map()); const [selectedId, setSelectedId] = useState(null); const events = useRef(0);
  const report = (cardDomCount, selectedCount = 0) => onStatus?.({ diagramReady: true, viewReady: true, rendered: true, nodeCount: 1, linkCount: 0, htmlDomCount: 1, buttonDomCount: 0, cardCount: cards.length, cardDomCount, selectedNodeCount: 0, cardExpanded: true, selectedCardCount: selectedCount, eventCount: events.current, lastEvent: selectedCount ? "카드 클릭 및 선택 스타일 적용" : "카드 선택 대기", consoleErrorCount: 0 });
  const initialize = () => { if (initialized.current) return; const coreView = viewRef.current?.find(); if (!coreView) return; initialized.current = true; const items = cards.map((card) => `<article data-card-id="${card.id}" data-interactive="true" tabindex="0" role="button" style="display:flex;gap:10px;align-items:center;padding:8px;border:2px solid transparent;border-radius:10px;background:white;cursor:pointer"><span style="display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:${card.color};color:white;font:700 15px sans-serif">${card.nickname[0]}</span><div><strong style="display:block;color:#17345f;font:700 14px sans-serif">${card.nickname}</strong><span style="color:#61708a;font:12px sans-serif">${card.intro}</span></div></article>`).join(""); const node = new ControlNode(coreView); node.template = `<section data-mf-card-node="14-04" style="box-sizing:border-box;width:100%;height:100%;display:grid;gap:7px;padding:10px;border:2px solid #2877de;border-radius:14px;background:#edf5ff">${items}</section>`; node.bounds = new Rect(53, 8, 130, 80); diagram.addItem(node); };
  const domCreated = (_sender, args) => { const items = [...args.node.getContent().querySelectorAll("[data-card-id]")]; items.forEach((item) => { const choose = () => { items.forEach((other) => { other.style.borderColor = "transparent"; other.style.background = "white"; other.setAttribute("aria-pressed", "false"); }); item.style.borderColor = "#2468d6"; item.style.background = "#eaf3ff"; item.setAttribute("aria-pressed", "true"); const id = Number(item.dataset.cardId); events.current += 1; setSelectedId(id); report(items.length, 1); }; const key = (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); choose(); } }; item.addEventListener("click", choose); item.addEventListener("keydown", key); listeners.current.set(item, { choose, key }); }); report(items.length, 0); };
  useEffect(() => () => { listeners.current.forEach(({ choose, key }, item) => { item.removeEventListener("click", choose); item.removeEventListener("keydown", key); }); listeners.current.clear(); diagram.clearAll(); }, [diagram]);
  return <div data-testid="diagram-demo"><p data-testid="card-selection-state">{selectedId ? `카드 ${selectedId} 선택됨` : "선택된 카드 없음"}</p><div style={{ height: 460 }}><DiagramView ref={viewRef} diagram={diagram} behavior={Behavior.Modify} onControlLoaded={initialize} onNodeDomCreated={domCreated} style={{ width: "100%", height: "100%" }} /></div></div>;
}
